/*
 * This file is part of the µOS++ distribution.
 *   (https://github.com/micro-os-plus)
 * Copyright (c) 2015 Liviu Ionescu.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom
 * the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#include <micro-os-plus/architecture.h>
#include <micro-os-plus/diag/trace.h>
#include <micro-os-plus/startup/initialize-hooks.h>

#include <stdint.h>
#include <stdlib.h>
#include <sys/types.h>

// ----------------------------------------------------------------------------
// This file defines the startup code for a portable embedded
// C/C++ application, built with newlib.
//
// Control reaches here from the reset handler via jump or call.
//
// The actual steps performed by _start are:
// - copy the initialised data region(s)
// - clear the BSS region(s)
// - initialise the system
// - run the preinit/init array (for the C++ static constructors)
// - initialise the arc/argv
// - branch to main()
// - run the fini array (for the C++ static destructors)
// - call _exit(), directly or via exit()
//
// If OS_INCLUDE_STARTUP_INIT_MULTIPLE_RAM_SECTIONS is defined, the
// code is capable of initialising multiple regions.
//
// The normal configuration is standalone, with all support
// functions implemented locally.
//
// For this to be called, the project linker must be configured without
// the startup sequence (-nostartfiles).
// ----------------------------------------------------------------------------

#if !defined(OS_INCLUDE_STARTUP_GUARD_CHECKS)
#define OS_BOOL_STARTUP_GUARD_CHECKS (true)
#endif

// ----------------------------------------------------------------------------

// All below symbols should be defined in the linker script.
#if !defined(OS_INCLUDE_STARTUP_INIT_MULTIPLE_RAM_SECTIONS)

// Begin address for the initialisation values of the .data section.
extern uint32_t __data_load_addr__;
// Begin address for the .data section.
extern uint32_t __data_begin__;
// End address for the .data section.
extern uint32_t __data_end__;

// Begin address for the .bss section.
extern uint32_t __bss_begin__;
// End address for the .bss section.
extern uint32_t __bss_end__;

#else

// The following symbols are constructs generated by the linker, indicating
// the location of various points in the "Memory regions initialisation arrays".
// These arrays are created by the linker via the managed linker script
// of each RW data mechanism. It contains the load address, execution address
// and length section and the execution and length of each BSS (zero
// initialised) section.
extern uint32_t __data_regions_array_begin__;
extern uint32_t __data_regions_array_end__;
extern uint32_t __bss_regions_array_begin__;
extern uint32_t __bss_regions_array_end__;

#endif

extern uint32_t __heap_begin__;
extern uint32_t __heap_end__;

extern "C" int
main (int argc, char* argv[]);

// ----------------------------------------------------------------------------

// Forward declarations

extern "C"
{
  void
  _start (void);

  static void
  os_initialize_data (uint32_t* from, uint32_t* region_begin,
		      uint32_t* region_end);

  static void
  os_initialize_bss (uint32_t* region_begin, uint32_t* region_end);

  static void
  os_run_init_array (void);

  // Not static since it is called from exit()
  void
  os_run_fini_array (void);
}

// ----------------------------------------------------------------------------

inline __attribute__((always_inline))
void
os_initialize_data (uint32_t* from, uint32_t* region_begin,
		    uint32_t* region_end)
{
  // Iterate and copy word by word.
  // It is assumed that the pointers are word aligned.
  uint32_t* p = region_begin;
  while (p < region_end)
    {
      *p++ = *from++;
    }
}

inline __attribute__((always_inline))
void
os_initialize_bss (uint32_t* region_begin, uint32_t* region_end)
{
  // Iterate and clear word by word.
  // It is assumed that the pointers are word aligned.
  uint32_t* p = region_begin;
  while (p < region_end)
    {
      *p++ = 0;
    }
}

// These magic symbols are provided by the linker. newlib standard.
extern void
(*__preinit_array_begin__[]) (void) __attribute__((weak));
extern void
(*__preinit_array_end__[]) (void) __attribute__((weak));
extern void
(*__init_array_begin__[]) (void) __attribute__((weak));
extern void
(*__init_array_end__[]) (void) __attribute__((weak));
extern void
(*__fini_array_begin__[]) (void) __attribute__((weak));
extern void
(*__fini_array_end__[]) (void) __attribute__((weak));

// Iterate over all the preinit/init routines (mainly static constructors).
inline __attribute__((always_inline))
void
os_run_init_array (void)
{
  os::trace::printf ("%s()\n", __func__);

  int count = __preinit_array_end__ - __preinit_array_begin__;
  for (int i = 0; i < count; i++)
    {
      __preinit_array_begin__[i] ();
    }

  // If the application needs to run the code in the .init section,
  // please use the startup files, since this requires the code in
  // crti.o and crtn.o to add the function prologue/epilogue.
  //_init(); // DO NOT ENABLE THIS!

  count = __init_array_end__ - __init_array_begin__;
  for (int i = 0; i < count; i++)
    {
      __init_array_begin__[i] ();
    }
}

// Run all the cleanup routines (mainly static destructors).
void
os_run_fini_array (void)
{
  os::trace::printf ("%s()\n", __func__);

  int count = __fini_array_end__ - __fini_array_begin__;
  for (int i = count; i > 0; i--)
    {
      __fini_array_begin__[i - 1] ();
    }

  // If the application needs to run the code in the .fini section,
  // please use the startup files, since this requires the code in
  // crti.o and crtn.o to add the function prologue/epilogue.
  //_fini(); // DO NOT ENABLE THIS!
}

#if defined(DEBUG) && (OS_BOOL_STARTUP_GUARD_CHECKS)

// These definitions are used to check if the routines used to
// clear the BSS and to copy the initialised DATA perform correctly.

#define BSS_GUARD_BAD_VALUE (0xCADEBABA)

static uint32_t volatile __attribute__ ((section(".bss_begin")))
__bss_begin_guard;
static uint32_t volatile __attribute__ ((section(".bss_end")))
__bss_end_guard;

#define DATA_GUARD_BAD_VALUE (0xCADEBABA)
#define DATA_BEGIN_GUARD_VALUE (0x12345678)
#define DATA_END_GUARD_VALUE (0x98765432)

static uint32_t volatile __attribute__ ((section(".data_begin")))
__data_begin_guard = DATA_BEGIN_GUARD_VALUE;

static uint32_t volatile __attribute__ ((section(".data_end")))
__data_end_guard = DATA_END_GUARD_VALUE;

#endif // defined(DEBUG) && (OS_BOOL_STARTUP_GUARD_CHECKS)

/**
 * @details
 * This is the place where the MCU will go immediately
 * after reset (on Cortex-M the `Reset_Handler` calls this function).
 *
 * To reach this location, the reset stack must point to a valid
 * internal RAM area.
 *
 * Debugging new startup configurations usually begins with placing
 * a breakpoint at `_start()`, and stepping through the routine.
 */
void
__attribute__ ((noreturn,weak))
_start (void)
{

  // --------------------------------------------------------------------------

  // Initialise hardware right after reset, to switch clock to higher
  // frequency and have the rest of the initialisations run faster.
  //
  // Also useful on platform with external RAM, that need to be
  // initialised before filling the BSS section.

  os_startup_initialize_hardware_early ();

  // Use Old Style DATA and BSS section initialisation,
  // that will manage a single BSS sections.

#if defined(DEBUG) && (OS_BOOL_STARTUP_GUARD_CHECKS)

  __data_begin_guard = DATA_GUARD_BAD_VALUE;
  __data_end_guard = DATA_GUARD_BAD_VALUE;

#endif

#if !defined(OS_INCLUDE_STARTUP_INIT_MULTIPLE_RAM_SECTIONS)

  // Copy the DATA segment from flash to RAM (inlined).
  os_initialize_data (&__data_load_addr__, &__data_begin__, &__data_end__);

#else

  // Copy all DATA sections from flash to RAM.
  for (uint32_t* p = &__data_regions_array_begin__;
      p < &__data_regions_array_end__;)
    {
      uint32_t* from = (uint32_t*) (*p++);
      uint32_t* region_begin = (uint32_t*) (*p++);
      uint32_t* region_end = (uint32_t*) (*p++);

      os_initialize_data (from, region_begin, region_end);
    }

#endif

#if defined(DEBUG) && (OS_BOOL_STARTUP_GUARD_CHECKS)

  if ((__data_begin_guard != DATA_BEGIN_GUARD_VALUE)
      || (__data_end_guard != DATA_END_GUARD_VALUE))
    {
      while (true)
	{
	  riscv::arch::nop ();
	}
    }

#endif

#if defined(DEBUG) && (OS_BOOL_STARTUP_GUARD_CHECKS)

  __bss_begin_guard = BSS_GUARD_BAD_VALUE;
  __bss_end_guard = BSS_GUARD_BAD_VALUE;

#endif

#if !defined(OS_INCLUDE_STARTUP_INIT_MULTIPLE_RAM_SECTIONS)

  // Zero fill the BSS section (inlined).
  os_initialize_bss (&__bss_begin__, &__bss_end__);

#else

  // Zero fill all BSS segments.
  for (uint32_t* p = &__bss_regions_array_begin__;
      p < &__bss_regions_array_end__;)
    {
      uint32_t* region_begin = (uint32_t*) (*p++);
      uint32_t* region_end = (uint32_t*) (*p++);

      os_initialize_bss (region_begin, region_end);
    }

#endif

#if defined(DEBUG) && (OS_BOOL_STARTUP_GUARD_CHECKS)

  if ((__bss_begin_guard != 0) || (__bss_end_guard != 0))
    {
      while (true)
	{
	  riscv::arch::nop ();
	}
    }

#endif

  // Hook to continue the initialisations. Usually compute and store the
  // clock frequency in a global variable, cleared above.
  os_startup_initialize_hardware ();

  // Initialise the trace output device. From this moment on,
  // os::trace::printf() calls are available (including in static constructors).
  os::trace::initialize ();

  os::trace::printf ("Hardware initialised.\n");

  os_startup_initialize_free_store (
      &__heap_begin__,
      (size_t) ((char*) (&__heap_end__) - (char*) (&__heap_begin__)));

  // Get the argc/argv (useful in semihosting configurations).
  int argc;
  char** argv;
  os_startup_initialize_args (&argc, &argv);

  // Call the standard library initialisation (mandatory for C++ to
  // execute the static objects constructors).
  os_run_init_array ();

  // Call the main entry point, and save the exit code.
  int code = main (argc, argv);

  // Standard program termination;
  // `atexit()` and C++ static destructors are executed.
  exit (code);
  /* NOTREACHED */
}

// ----------------------------------------------------------------------------

#if !defined(OS_USE_SEMIHOSTING_SYSCALLS)

// Semihosting uses a more elaborate version of os_startup_initialize_args()
// to parse args received from host.

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"

// This is the standard default implementation for the routine to
// process args. It returns a single empty arg.
//
// For semihosting applications, this is redefined to get the real
// args from the debugger.
//
// The application can redefine it to fetch some args from a
// non-volatile memory.

void __attribute__((weak))
os_startup_initialize_args (int* p_argc, char*** p_argv)
{
  // By the time we reach this, the data and bss should have been initialised.

  // The strings pointed to by the argv array shall be modifiable by the
  // program, and retain their last-stored values between program startup
  // and program termination. (static, no const)
  static char name[] = "";

  // The string pointed to by argv[0] represents the program name;
  // argv[0][0] shall be the null character if the program name is not
  // available from the host environment. argv[argc] shall be a null pointer.
  // (static, no const)
  static char* argv[2] =
    { name, NULL };

  *p_argc = 1;
  *p_argv = &argv[0];

  return;
}

#pragma GCC diagnostic pop

/**
 * @details
 * This function resets the MCU core, if possible.
 */
void
__attribute__ ((noreturn,weak))
os_terminate (int code __attribute__((unused)))
{
#if defined(__ARM_EABI__)
  NVIC_SystemReset ();
#elif defined(__riscv)
  // TODO: find a RISC-V soft reset
#endif
  while (true)
    {
      ;
    }
  /* NOTREACHED */
}

#endif /* !defined(OS_USE_SEMIHOSTING_SYSCALLS) */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"

// Redefine this function to initialise the free store.
void __attribute__((weak))
os_startup_initialize_free_store (void* heap_address, size_t heap_size_bytes)
{
  ;
}

// Redefine this function to display memory allocator reports or
// other statistics.
void __attribute__((weak))
os_terminate_goodbye (void)
{
  os::trace::printf ("\nHasta la Vista!\n");
}

#pragma GCC diagnostic pop

// ----------------------------------------------------------------------------
